token:

user_id:
fastapi_swapper:
bot_path: https://api.telegram.org/file/bot
bot_name: Adjuface_bot
language: en
img_delay: 2
hour_interval: 48
premium_days: 30
free_requests: 2
premium_requests: 30
premium_targets: 10

db_name:
db_type:
util_folder:

tts_auth:
stt_link:
tts_link:
tts_token:
tts_audio_size: 59000

currency_api: https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@latest/v1/currencies/
currency_url: https://currency-api.pages.dev/v1/currencies/

weather_url: http://api.openweathermap.org/data/2.5/weather?lat={latitude}&lon={longitude}&appid={api_key}&lang={lang}&units=metric
weather_api:

adjupay:
you_token:
you_num:
price: